// src/declarations.d.ts
// Type declarations for non-TypeScript imports.

// Virtual doc folder modules — generated by docFolderPlugin in esbuild.config.mjs.
// Each module exports a Record<string, string> where keys are filenames (without .md)
// and values are the file contents.
declare module "forge:docs" {
  const docs: Record<string, string>;
  export default docs;
}

declare module "forge:examples" {
  const examples: Record<string, string>;
  export default examples;
}
